---
- name: Query astros api with Ansible
  hosts: localhost     # we just want to make an HTTP request
  connection: local    # do not SSH anywhere (including to yourself)
  gather_facts: no     # set to true by default, runs the "setup" module
  
    
  tasks:

         - name: Make an API request with HTTP GET
           uri:
                 url: http://api.open-notify.org/astros.json
                 method: GET
           register: astrojson       # the "register" keyword is not part of the uri module
                                     # just like the "become" keyword, this augments how a module executes
                                     # in this case, we want to save the response returned by this module
                                     # ALL modules in Ansible return data. Think of it as the "results" of how the
                                     # task ran.
                                     
         - name: Display the contents of the variable astrojson
           debug:
                 var: astrojson

         - name: Display the contents of the variable astrojson.json
           debug:
                 var: astrojson.json

         - name: Display the contents of the variable astrojson.json.number
           debug:
                 var: astrojson.json.number
