---
- name: Learning about the loop keyword
  hosts: localhost
  gather_facts: false
  connection: local
   
  vars:
    my_list:
    - "1) A hyphen represents an item on a list"
    - "2) So the second item on the list is this"
    - "3) Whereas this would be the third"
    - "4) Item var is always replaced by an item from the with_items list"
    my_listB:
    - "5) Here is another list"
    - "6) We use double quotes to clearly indicate start and end of a string"
    - '7) Single quotes are okay as well'
    day: "thursday"
    week: "last"
    month: "feb"    

  tasks:
   - name: "List of awesome Ansible modules"
     debug:
       msg: "This is loop number {{ countdracula }}. The debug module allows us to print to the screen --> {{ pwd }}"
     loop: "{{ my_list }} + {{ my_listB }}"
     loop_control:
             loop_var: pwd # this is the new value of "item"
             index_var: countdracula # this should be a counter of how many times the loop ran
